from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication
import sys
import time
from math import pi


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1247, 818)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("logo_gaul.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(200, 200, 200);")
        MainWindow.setIconSize(QtCore.QSize(35, 25))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.line_15 = QtWidgets.QFrame(self.centralwidget)
        self.line_15.setStyleSheet("background-color: rgb(200, 0, 0);")
        self.line_15.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.horizontalLayout_7.addWidget(self.line_15)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.line_12 = QtWidgets.QFrame(self.centralwidget)
        self.line_12.setStyleSheet("background-color: rgb(200, 0, 0);")
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.gridLayout_2.addWidget(self.line_12, 3, 1, 1, 1)
        self.line_17 = QtWidgets.QFrame(self.centralwidget)
        self.line_17.setStyleSheet("background-color: rgb(200, 0, 0);")
        self.line_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.gridLayout_2.addWidget(self.line_17, 0, 2, 1, 1)
        self.line_11 = QtWidgets.QFrame(self.centralwidget)
        self.line_11.setStyleSheet("background-color: rgb(200, 0, 0);")
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.gridLayout_2.addWidget(self.line_11, 1, 1, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Thames")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.horizontalLayout_8.addLayout(self.verticalLayout_5)
        self.verticalLayout_11.addWidget(self.groupBox_2)
        self.line_39 = QtWidgets.QFrame(self.centralwidget)
        self.line_39.setStyleSheet("background-color: rgb(200, 0, 0);")
        self.line_39.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_39.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_39.setObjectName("line_39")
        self.verticalLayout_11.addWidget(self.line_39)
        self.verticalLayout_10.addLayout(self.verticalLayout_11)
        self.horizontalLayout_5.addLayout(self.verticalLayout_10)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 3, 2, 1, 1)
        self.line_10 = QtWidgets.QFrame(self.centralwidget)
        self.line_10.setStyleSheet("background-color: rgb(200, 0, 0);")
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.gridLayout_2.addWidget(self.line_10, 2, 0, 1, 1)
        self.line_16 = QtWidgets.QFrame(self.centralwidget)
        self.line_16.setStyleSheet("background-color: rgb(200, 0, 0);\n"
"")
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.gridLayout_2.addWidget(self.line_16, 0, 0, 1, 1)
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setStyleSheet("background-color: rgb(200, 0, 0);")
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout_2.addWidget(self.line_9, 2, 2, 1, 1)
        self.openGLWidget_gaul = QtWidgets.QOpenGLWidget(self.centralwidget)
        self.openGLWidget_gaul.setObjectName("openGLWidget_gaul")
        self.gridLayout_2.addWidget(self.openGLWidget_gaul, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Thames")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.groupBox.setFont(font)
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.groupBox.setTitle("")
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setFlat(True)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.pushButton_begin = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        self.pushButton_begin.setFont(font)
        self.pushButton_begin.setStyleSheet("background-color: rgb(195, 195, 195);")
        self.pushButton_begin.setObjectName("pushButton_begin")
        self.verticalLayout.addWidget(self.pushButton_begin)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        # self.checkBox_datafile = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        # self.checkBox_datafile.setFont(font)
        # self.checkBox_datafile.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        # self.checkBox_datafile.setObjectName("checkBox_datafile")
        # self.verticalLayout.addWidget(self.checkBox_datafile)
        # self.pushButton_serial = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(False)
        # self.pushButton_serial.setFont(font)
        # self.pushButton_serial.setStyleSheet("background-color: rgb(200, 200, 200);")
        # self.pushButton_serial.setAutoDefault(False)
        # self.pushButton_serial.setDefault(False)
        # self.pushButton_serial.setFlat(False)
        # self.pushButton_serial.setObjectName("pushButton_serial")
        # self.verticalLayout.addWidget(self.pushButton_serial)
        # self.pushButton_fullgraph = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        # self.pushButton_fullgraph.setFont(font)
        # self.pushButton_fullgraph.setStyleSheet("background-color: rgb(195, 195, 195);")
        # self.pushButton_fullgraph.setObjectName("pushButton_fullgraph")
        # self.verticalLayout.addWidget(self.pushButton_fullgraph)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.lcdNumber_time = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdNumber_time.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lcdNumber_time.setFont(font)
        self.lcdNumber_time.setAutoFillBackground(False)
        self.lcdNumber_time.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdNumber_time.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lcdNumber_time.setSmallDecimalPoint(True)
        self.lcdNumber_time.setDigitCount(6)
        self.lcdNumber_time.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_time.setProperty("intValue", 0)
        self.lcdNumber_time.setObjectName("lcdNumber_time")
        self.verticalLayout.addWidget(self.lcdNumber_time)
        self.horizontalLayout.addWidget(self.groupBox)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 2, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_4.addWidget(self.line_5)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_4.addWidget(self.line_4)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_4.addWidget(self.line_3)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout_4.addWidget(self.line_6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout_6.addLayout(self.verticalLayout_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lcdNumber_roll = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_roll.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(214, 0, 0);")
        self.lcdNumber_roll.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber_roll.setSmallDecimalPoint(True)
        self.lcdNumber_roll.setDigitCount(6)
        self.lcdNumber_roll.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_roll.setProperty("value", 0.0)
        self.lcdNumber_roll.setProperty("intValue", 0)
        self.lcdNumber_roll.setObjectName("lcdNumber_roll")
        self.horizontalLayout_6.addWidget(self.lcdNumber_roll)
        self.lcdNumber_pitch = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_pitch.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"color: rgb(0, 136, 11);")
        self.lcdNumber_pitch.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber_pitch.setSmallDecimalPoint(True)
        self.lcdNumber_pitch.setDigitCount(6)
        self.lcdNumber_pitch.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_pitch.setObjectName("lcdNumber_pitch")
        self.horizontalLayout_6.addWidget(self.lcdNumber_pitch)
        self.lcdNumber_yaw = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_yaw.setMinimumSize(QtCore.QSize(0, 40))
        self.lcdNumber_yaw.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"color: rgb(0, 76, 229);")
        self.lcdNumber_yaw.setFrameShape(QtWidgets.QFrame.Box)
        self.lcdNumber_yaw.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber_yaw.setLineWidth(1)
        self.lcdNumber_yaw.setSmallDecimalPoint(True)
        self.lcdNumber_yaw.setDigitCount(6)
        self.lcdNumber_yaw.setMode(QtWidgets.QLCDNumber.Dec)
        self.lcdNumber_yaw.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_yaw.setProperty("value", 0.0)
        self.lcdNumber_yaw.setProperty("intValue", 0)
        self.lcdNumber_yaw.setObjectName("lcdNumber_yaw")
        self.horizontalLayout_6.addWidget(self.lcdNumber_yaw)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.graphicsView_livegraph = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_livegraph.setStyleSheet("\n"
"background-color: rgb(237, 242, 244);")
        self.graphicsView_livegraph.setObjectName("graphicsView_livegraph")
        self.horizontalLayout_2.addWidget(self.graphicsView_livegraph)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.line_19 = QtWidgets.QFrame(self.centralwidget)
        self.line_19.setStyleSheet("background-color: rgb(200, 0, 0);")
        self.line_19.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.verticalLayout_6.addWidget(self.line_19)
        self.gridLayout_2.addLayout(self.verticalLayout_6, 3, 0, 1, 1)
        self.horizontalLayout_7.addLayout(self.gridLayout_2)
        self.line_18 = QtWidgets.QFrame(self.centralwidget)
        self.line_18.setStyleSheet("background-color: rgb(200, 0, 0);")
        self.line_18.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.horizontalLayout_7.addWidget(self.line_18)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionUpload_a_model = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/actionOpenGL/arrow-up-upload-black.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUpload_a_model.setIcon(icon1)
        self.actionUpload_a_model.setObjectName("actionUpload_a_model")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/actionOpenGL/gear-icon-14.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSettings.setIcon(icon2)
        self.actionSettings.setObjectName("actionSettings")
        self.actionZoom_out = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/actionOpenGL/Zoom_out.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoom_out.setIcon(icon3)
        self.actionZoom_out.setObjectName("actionZoom_out")
        self.actionZoom_in = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/actionOpenGL/zoom-in-256.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoom_in.setIcon(icon4)
        self.actionZoom_in.setObjectName("actionZoom_in")
        self.action = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/actionOpenGL/bw-arrows-circular.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action.setIcon(icon5)
        self.action.setObjectName("action")
        self.actionSerial_connection = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/actionOpenGL/Computer-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSerial_connection.setIcon(icon6)
        self.actionSerial_connection.setObjectName("actionSerial_connection")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/actionOpenGL/256-256-5522ef02c3bcb2c8389eda0bbc2f4815.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_as.setIcon(icon7)
        self.actionSave_as.setObjectName("actionSave_as")
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.pushButton_begin.clicked.connect(self.measurement)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GAUL LiveGyro"))
        self.groupBox.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:400;\">Press &quot;Begin measurement&quot; to initiate the saving of the live data into a file.</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "Measurement"))
        self.pushButton_begin.setText(_translate("MainWindow", "Begin measurement"))
        # self.checkBox_datafile.setText(_translate("MainWindow", "Brute data to file"))
        # self.pushButton_serial.setText(_translate("MainWindow", "Serial connection"))
        # self.pushButton_fullgraph.setText(_translate("MainWindow", "Complete graph"))
        self.label_5.setText(_translate("MainWindow", "TIME"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">ROLL</p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">PITCH</p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">YAW</p></body></html>"))
        self.actionUpload_a_model.setText(_translate("MainWindow", "Upload a model"))
        self.actionUpload_a_model.setToolTip(_translate("MainWindow", "Upload"))
        self.actionUpload_a_model.setShortcut(_translate("MainWindow", "Ctrl+U"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionSettings.setToolTip(_translate("MainWindow", "Settings"))
        self.actionSettings.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionZoom_out.setText(_translate("MainWindow", "Zoom out"))
        self.actionZoom_out.setShortcut(_translate("MainWindow", "Ctrl+Alt++"))
        self.actionZoom_in.setText(_translate("MainWindow", "Zoom in"))
        self.actionZoom_in.setShortcut(_translate("MainWindow", "Ctrl+Alt+-"))
        self.action.setText(_translate("MainWindow", "Rotation mode"))
        self.action.setToolTip(_translate("MainWindow", "the mouse becomes a rotation point"))
        self.action.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionSerial_connection.setText(_translate("MainWindow", "Serial connection"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as"))
        self.actionSave_as.setToolTip(_translate("MainWindow", "Saves last measurement"))
        self.actionSave_as.setShortcut(_translate("MainWindow", "Ctrl+S"))

    def measurement(self):
        while True:
            with open('datatmp.txt') as myfile:
                try:
                    t, x, y, z = list(myfile)[-1].split('#')
                except ValueError:
                    pass
            self.lcdNumber_time.display(round(int(t)/1000))
            self.lcdNumber_roll.display((int(x)/5) * pi/180)
            self.lcdNumber_pitch.display((512/5 - int(y)/5) * pi/180)
            self.lcdNumber_yaw.display((512/5 - int(z)/5) * pi/180)
            QApplication(sys.argv).processEvents()
            time.sleep(0.1)
